services:
  # Criando um container MYSQL com persistência
  banco-dados:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dados_sql:/var/lib/mysql # Replicando volume (Persistência)

  # Criando um proxy utilizando o NGINX
  servidor-proxy:
    image: nginx:latest
    ports:
      - "80:80" # Porta para acesso externo
    depends_on:
      - banco-dados

volumes:
  dados_sql: # Volume gerenciado pelo Docker